### ISSUE TITLE
Upgrade scripts fails due to E2BIG error

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1046]
**Describe the bug:** (a clear and concise description of what the bug is)
I happens that the upgrade scripts yield about too long parameters provided to a shell.
Unfortunately, I am not sure what exactly is causing that issue. 

The scripts are encoded in the `upgrades.yaml` file and executed by in the upgrade() function from the `src/cmd/upgrade.ts` file.

**To Reproduce**
1. Trigger Otomi Drone pipeline: 
1. See error

```
Upgrade records detected for version dev
2023-03-06T12:57:01.070Z otomi:global:error Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:700:9)
    at Promise.promise._run (/home/app/stack/node_modules/zx/dist/bundle.cjs:15252:30)
    at Promise.then (/home/app/stack/node_modules/zx/dist/bundle.cjs:15382:25)
```

**Expected behavior:** (a clear and concise description of what you expected to happen)

**Screenshots:** (if applicable, add screenshots to help explain your problem)

- Core Version v0.18.0, v0.18.1
- cloud: azure
- cluster:  1.23

**Comment by j-zimnowoda** [comment]
E2BIG comes error from the `gucci` function, which is called in the `upgrade.ts` file.
It turns out that this function convert all values to command line arguments, which causes the error.
