### ISSUE TITLE
otomi installer job fails due to failed authentication for gitea

### ISSUE THREAD

**Issue by armantur** [redkubes/otomi-core#1050]
**Describe the bug:** (a clear and concise description of what the bug is)

`otomi` installer job is failing due to gitea authorization error. The log from the installer job:

```
Current version of otomi: 0.18.1
2023-03-10T17:25:33.338Z otomi:cmd:validate-values:validateValues:log Values validation STARTED
2023-03-10T17:25:33.439Z otomi:cmd:validate-values:validateValues:info Loading values-schema.yaml
2023-03-10T17:25:34.000Z otomi:cmd:validate-values:validateValues:info Validating values
2023-03-10T17:25:34.023Z otomi:cmd:validate-values:validateValues:log Values validation SUCCESSFUL
2023-03-10T17:25:34.023Z otomi:cmd:commit:commit:info Preparing values
2023-03-10T17:25:34.266Z otomi:cmd:bootstrap:bootstrapGit:info Git repo was already bootstrapped
2023-03-10T17:25:34.783Z otomi:cmd:gen-drone:genDrone:log gen-drone is finished and the pipeline configuration is written to: /home/app/stack/env/.drone.yml
2023-03-10T17:25:34.784Z otomi:common:crypt:encrypt:info Skipping encryption
2023-03-10T17:25:34.784Z otomi:cmd:commit:commitAndPush:info Committing values
2023-03-10T17:25:34.878Z otomi:cmd:commit:commitAndPush:error remote: Unauthorized
fatal: Authentication failed for 'https://gitea.otomi.example.com/otomi/values.git/'

2023-03-10T17:25:34.879Z otomi:global:error Error: Origin does not exist yet
    at commitAndPush (/home/app/stack/dist/src/cmd/commit.js:63:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async commit (/home/app/stack/dist/src/cmd/commit.js:85:5)
    at async applyAll (/home/app/stack/dist/src/cmd/apply.js:72:13)
    at async apply (/home/app/stack/dist/src/cmd/apply.js:80:9)
    at async Object.handler (/home/app/stack/dist/src/cmd/apply.js:100:9)
```

**To Reproduce**

1. Create EKS cluster v1.23 with 3 worker nodes in us-east-1 region.
2. Create Route53 hosted zone (in this case example.com)
3. Create IAM user with API credentials that has permissions required for external-dns and cert-manager.
4. Install otomi v1.8.1 with Helm chart 0.5.29 using the following values:
```
cluster:
  domainSuffix: 'otomi.example.com'
  k8sVersion: '1.23'
  name: 'otomi'
  region: 'us-east-1'
  apiName: 'otomi'
  provider: 'aws'

otomi:
  hasExternalDNS: true

apps:
  cert-manager:
    issuer: letsencrypt
    email: 'otomi@example.com'
    stage: production
dns:
  domainFilters:
    - example.com
  provider:
    aws:
      credentials:
        accessKey: 'VALID_ACCESS_KEY_CREATED_IN_STEP_3'
        secretKey: 'VALID_SECRET_KEY_CREATED_IN_STEP_3'
      region: 'us-east-1'
```

4. Wait until otomi installer job starts failing.
5. See the error in the job pod logs.

**Expected behavior:**

Otomi installer job succeeds and outputs login/password in the logs.

**Cluster(s):**

- Cloud: aws
- Cluster: EKS 1.23

**Versions:** (seen in console's `/settings`)

- Core Version 0.18.1
- Console Version: aws
- API version: not known since the console shows nothing due to the failed installation.

**Additional context:** (add any other context about the problem here)

This error doesn't appear if `hasExternalDNS` is set to `false`.

**Comment by srodenhuis** [comment]
Can you see the certs are created and ACTIVE=true?

cert-manager needs to be able to add records to Route53 in order to solve the DNS01 challenge. To enable this, create a IAM policy with the following permissions:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "route53:GetChange",
            "Resource": "arn:aws:route53:::change/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "route53:ChangeResourceRecordSets",
                "route53:ListResourceRecordSets"
            ],
            "Resource": [
                "arn:aws:route53:::hostedzone/xxxxxxxxxxxxxxxxxx"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "route53:ListHostedZonesByName",
                "route53:ListHostedZones"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Comment by armantur** [comment]
Yes, all certificates were successfully requested by `cert-manager` and issued by Let's Encrypt for all Otomi records (keycloak, gitea, otomi, etc) and I can see issued certificates in the k8s cluster.

I can access `https://otomi.otomi.example.com` which has a valid certificate but getting a white page after successful login.

**Comment by srodenhuis** [comment]
I see this issue looks the same as #926 
The work around for now is to define the otomi.adminPassword in your values

**Comment by armantur** [comment]
Once `otomi.adminPassword` value was set, `otomi` started without any issues. Thank you for your help!
