### ISSUE TITLE
new handleFileEntry expects VALUES_INPUT and breaks drone runner

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#1081]
**Describe the bug:** (a clear and concise description of what the bug is)

output from runner:
```
2023-04-14T09:35:37.688Z otomi:global:error Error: undefined does not exist
    at Object.loadYaml (/home/app/stack/dist/src/common/utils.js:63:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handleFileEntry (/home/app/stack/dist/src/cmd/bootstrap.js:242:29)
    at async bootstrap (/home/app/stack/dist/src/cmd/bootstrap.js:373:5)
    at async Object.handler (/home/app/stack/dist/src/cmd/bootstrap.js:401:9)
```

**To Reproduce**

1. Activate drone
2. do anything to trigger drone

**Expected behavior:** (a clear and concise description of what you expected to happen)

The code should NOT expect `VALUES_INPUT` in the context of the runner.

**Comment by Morriz** [comment]
@ElderMatt please take a look

**Comment by ElderMatt** [comment]
I will take a look at it right now.
