### ISSUE TITLE
The Otomi API fails to find the otomi-values repository on Git

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#222]
**Describe the bug:** (a clear and concise description of what the bug is)

I attempt to run 'otomi console' from my otomi-values repository. It doesn't work "out of the box". 

**To Reproduce**
1. Follow these steps:

```
:::info Otomi Enterprise Edition license needed

If you have a license for Otomi EE you can run the console locally for initial configuration. The console allows for easy configuration of many settings but not all. Please return to the [Configuration](configuration) section to read more about this.

:::

If you have not done so already, put the pullsecret you have been given in `secrets.settings.yaml` under `otomi.pullSecret`. Make sure the git details are correctly added to 'charts/\*otomi-api.yaml'. Remember to use an access token with your Git provider (e.g. https://github.com/settings/tokens) and provide it as value for the 'password' key below.

repoUrl: github.com/redkubes/otomi-values-demo.git
email: some@secret.value
user: somesecretvalue
password: somesecretvalue

Make sure to set the GIT_REPO_URL environment variable in otomi-values/docker-compose.yml. Always start the console from the otomi-values repository and run otomi-values/docker-compose.yml to use the variables in the otomi-values repository.

${GIT_REPO_URL:-github.com/redkubes/otomi-values-demo.git}

You can now start the console.

otomi console
```
2. See the error:

```
api      | NODE_ENV:  production
api      | Checking if repo exists at: /tmp/otomi
api      | Repo does not exist. Cloning from: github.com/svatwork/otomi-values.git to: /tmp/otomi
api      | Unable to init app GitError: Cloning into '/tmp/otomi'...
api      | remote: Repository not found.
api      | fatal: Authentication failed for 'https://github.com/svatwork/otomi-values.git/'
api      |
api      |     at GitExecutorChain.onFatalException (/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)
api      |     at GitExecutorChain.<anonymous> (/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)
api      |     at Generator.throw (<anonymous>)
api      |     at rejected (/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
api      |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
api      |   task: {
api      |     commands: [
api      |       'clone',
api      |       'https://:@github.com/svatwork/otomi-values.git',
api      |       '/tmp/otomi'
api      |     ],
api      |     format: 'utf-8',
api      |     parser: [Function: parser]
api      |   }
api      | }
api      | Exiting
api exited with code 1
```

**Expected behavior:** (a clear and concise description of what you expected to happen)

Filled in all the correct values, so I expect to see the Otomi console working locally.

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**
 - Cloud: [e.g. aws]
 - Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)
 - Core Version: 0.11.50
 - Console Version: latest?
 - API version: latest? 

**Desktop:** (if relevant)
 - OS: MacOS
 - Browser 
 - Version 10.14.6

**Comment by Morriz** [comment]
Closed as this is due to a lack of documentation (or it wasnt read properly). The repo should be configured and pushed to remote before starting the console.  Updated just now in c3c77ad..39d26fe

**Comment by svatwork** [comment]
Just found out that `rm /tmp/otomi-env` removes the variables (confirmed by @Morriz). Will create a pull request.
