### ISSUE TITLE
Permission denied on accessing host directory in Docker

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#327]
##  Describe the bug

`otomi` cannot access files from the host if the host is not MacOS. See: https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker. This is solved on MacOS by OSXFS, but does not exist on Linux hosts.

<details><summary>Without `--user $(id -u):$(id -g)`</summary>

```
otomi-core git:(svatwork/bug/docker-linux-host-volumes) ✗ docker run --rm -v ${ENV_DIR}:${PWD}/env:z -v ${PWD}:${PWD} -w ${PWD} otomi/core:kubeapps rm CHANGELOG.md
rm: cannot remove 'CHANGELOG.md': Permission denied
```
```
otomi-core git:(svatwork/bug/docker-linux-host-volumes) ✗ docker run --rm -v ${ENV_DIR}:${PWD}/env:z -v ${PWD}:${PWD} -w ${PWD} otomi/core:kubeapps id             
uid=999(app) gid=999(app) groups=999(app)
```
```
otomi-core git:(svatwork/bug/docker-linux-host-volumes) ✗ docker run --rm -v ${ENV_DIR}:${PWD}/env:z -v ${PWD}:${PWD} -w ${PWD} otomi/core:kubeapps whoami
app
```
```
command "/home/app/tools/helm" exited with non-zero status:

PATH:
  /home/app/tools/helm

ARGS:
  0: helm (4 bytes)
  1: secrets (7 bytes)
  2: dec (3 bytes)
  3: /home/sv/projects/otomi-core/env/env/teams/secrets.demo.yaml (60 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/app/.kube/config
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/app/.kube/config
  /home/app/.local/share/helm/plugins/helm-secrets/secrets.sh: line 311: /home/sv/projects/otomi-core/env/env/teams/secrets.demo.yaml.dec: Permission denied
  rm: cannot remove '/home/sv/projects/otomi-core/env/env/teams/secrets.demo.yaml.dec': No such file or directory
  Error: plugin "secrets" exited with error

COMBINED OUTPUT:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/app/.kube/config
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/app/.kube/config
  /home/app/.local/share/helm/plugins/helm-secrets/secrets.sh: line 311: /home/sv/projects/otomi-core/env/env/teams/secrets.demo.yaml.dec: Permission denied
  rm: cannot remove '/home/sv/projects/otomi-core/env/env/teams/secrets.demo.yaml.dec': No such file or directory
  Error: plugin "secrets" exited with error
command "/home/app/tools/helm" exited with non-zero status:

...

in helmfile.d/helmfile-03.init.yaml: failed to read snippets/defaults.gotmpl: Failed loading environment secrets with 14 errors
```

</details>

<details><summary>With `--user $(id -u):$(id -g)`</summary>

```
PATH:
  /home/app/tools/helm

ARGS:
  0: helm (4 bytes)
  1: version (7 bytes)
  2: --client (8 bytes)
  3: --short (7 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

goroutine 1 [running]:
github.com/roboll/helmfile/pkg/helmexec.New(0x16db3cf, 0x4, 0xc000559160, 0x0, 0x0, 0x1ca0d80, 0xc000686ea0, 0xc0006527c0)
        /home/circleci/workspace/helmfile/pkg/helmexec/exec.go:89 +0x28e
github.com/roboll/helmfile/pkg/app.(*App).getHelm(0xc0000325a0, 0xc0004bf900, 0x0, 0x0)
        /home/circleci/workspace/helmfile/pkg/app/app.go:662 +0x261
github.com/roboll/helmfile/pkg/state.(*StateCreator).scatterGatherEnvSecretFiles(0xc000204480, 0xc0004bf900, 0xc000260400, 0xe, 0x10, 0xc0001c9530, 0x173c868, 0x1, 0x1)
        /home/circleci/workspace/helmfile/pkg/state/create.go:275 +0x98
github.com/roboll/helmfile/pkg/state.(*StateCreator).loadEnvValues(0xc000204480, 0xc0004bf900, 0x7ffdc0a21579, 0x7, 0xc0002f4f00, 0x0, 0x173c868, 0x173ce88, 0x7fd93c438e98, 0x0, ...)
        /home/circleci/workspace/helmfile/pkg/state/create.go:249 +0x78e
github.com/roboll/helmfile/pkg/state.(*StateCreator).LoadEnvValues(0xc000204480, 0xc0004be500, 0x7ffdc0a21579, 0x7, 0x0, 0x0, 0xc0000365a0, 0x18, 0xc0004be500)
        /home/circleci/workspace/helmfile/pkg/state/create.go:151 +0xda
github.com/roboll/helmfile/pkg/state.(*StateCreator).ParseAndLoad(0xc000204480, 0xc00044a000, 0x8634, 0xa102, 0x16da195, 0x1, 0xc0000365a0, 0x18, 0x7ffdc0a21579, 0x7, ...)
        /home/circleci/workspace/helmfile/pkg/state/create.go:189 +0x101
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).load(0xc0006097c0, 0xc00044a000, 0x8634, 0xa102, 0x16da195, 0x1, 0xc0000365a0, 0x18, 0xc0005e4000, 0x0, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:161 +0x11a
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).renderAndLoad(0xc0006097c0, 0x0, 0x0, 0x16da195, 0x1, 0xc0000365a0, 0x18, 0xc0001cc000, 0x4bd, 0x6bd, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:200 +0x4f2
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).loadFileWithOverrides(0xc0006097c0, 0x0, 0x0, 0x16da195, 0x1, 0xc000036520, 0x18, 0x0, 0x0, 0x0, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:113 +0x1ec
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).loadFile(...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:92
github.com/roboll/helmfile/pkg/state.(*StateCreator).loadBases(0xc000516580, 0x0, 0xc0000db180, 0x16da195, 0x1, 0x1, 0xc0000b9f80, 0x15)
        /home/circleci/workspace/helmfile/pkg/state/create.go:208 +0xe2
github.com/roboll/helmfile/pkg/state.(*StateCreator).ParseAndLoad(0xc000516580, 0xc000542600, 0x23, 0x40, 0x16da195, 0x1, 0xc0000b9f80, 0x15, 0x7ffdc0a21579, 0x7, ...)
        /home/circleci/workspace/helmfile/pkg/state/create.go:183 +0x2fc
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).load(0xc0006097c0, 0xc000542600, 0x23, 0x40, 0x16da195, 0x1, 0xc0000b9f80, 0x15, 0xc00015b901, 0x0, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:161 +0x11a
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).renderAndLoad(0xc0006097c0, 0x0, 0x0, 0x16da195, 0x1, 0xc0000b9f80, 0x15, 0xc000162000, 0x2a7, 0x4a7, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:200 +0x4f2
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).loadFileWithOverrides(0xc0006097c0, 0x0, 0x0, 0x16da195, 0x1, 0xc0000b95cb, 0x15, 0xc000079501, 0x199, 0x203000, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:113 +0x1ec
github.com/roboll/helmfile/pkg/app.(*desiredStateLoader).Load(0xc0006097c0, 0xc0000b95cb, 0x15, 0x279c918, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
        /home/circleci/workspace/helmfile/pkg/app/desired_state_file_loader.go:65 +0x2f8
github.com/roboll/helmfile/pkg/app.(*App).loadDesiredStateFromYaml(0xc0000325a0, 0xc0000b95cb, 0x15, 0xc00045b898, 0x1, 0x1, 0x1, 0x0, 0x0)
        /home/circleci/workspace/helmfile/pkg/app/app.go:628 +0x288
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1(0xc0000b95cb, 0x15, 0xc000542580, 0x32, 0x0, 0x0)
        /home/circleci/workspace/helmfile/pkg/app/app.go:680 +0x176
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles.func1(0xc00003a2d0, 0x27)
        /home/circleci/workspace/helmfile/pkg/app/app.go:594 +0x9d
github.com/roboll/helmfile/pkg/app.(*App).within(0xc0000325a0, 0xc0000b95c0, 0xa, 0xc00045bcb0, 0xc00045bc70, 0x2)
        /home/circleci/workspace/helmfile/pkg/app/app.go:555 +0x33e
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles(0xc0000325a0, 0x0, 0x0, 0x279c918, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
        /home/circleci/workspace/helmfile/pkg/app/app.go:588 +0x2f2
github.com/roboll/helmfile/pkg/app.(*App).visitStates(0xc0000325a0, 0x0, 0x0, 0x279c918, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
        /home/circleci/workspace/helmfile/pkg/app/app.go:673 +0x10b
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0xc0000325a0, 0x0, 0x0, 0xc00045bfd0, 0xc00045c038, 0x1, 0x1, 0xc00045bff0, 0x1329e89)
        /home/circleci/workspace/helmfile/pkg/app/app.go:928 +0x4c1
github.com/roboll/helmfile/pkg/app.(*App).ForEachState(0xc0000325a0, 0xc00045c040, 0xc00045c038, 0x1, 0x1, 0x40a118, 0x16c0160)
        /home/circleci/workspace/helmfile/pkg/app/app.go:809 +0xb2
github.com/roboll/helmfile/pkg/app.(*App).Template(0xc0000325a0, 0x1cd7fa0, 0xc00032a900, 0xc00032a900, 0xc000559160)
        /home/circleci/workspace/helmfile/pkg/app/app.go:234 +0xc8
main.main.func5(0xc0000325a0, 0xc0000fa6e0, 0x0, 0xc00032a8b0, 0x0)
        /home/circleci/workspace/helmfile/main.go:266 +0x6d
main.action.func1(0xc0000fa6e0, 0x0, 0xc0000d8460)
        /home/circleci/workspace/helmfile/main.go:781 +0xd4
github.com/urfave/cli.HandleAction(0x1439f20, 0xc000557780, 0xc0000fa6e0, 0xc0000fa6e0, 0x0)
        /home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/app.go:524 +0x11a
github.com/urfave/cli.Command.Run(0x16e0f28, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1722ba0, 0x3d, 0x0, ...)
        /home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/command.go:173 +0x57a
github.com/urfave/cli.(*App).Run(0xc0005c6000, 0xc0000bc120, 0x6, 0x6, 0x0, 0x0)
        /home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/app.go:277 +0x7c7
main.main()
        /home/circleci/workspace/helmfile/main.go:556 +0x3c96
```

</details>

<details><summary>Expected behavior (a clear and concise description of what you expected to happen)</summary>

1. Replace `otomi` image with custom built image, removed these lines from `otomi/tools`:

```
RUN chown -R app:app /home/app
USER app
```

```
otomi template
...
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - create
      - delete
      - get
      - list
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - delete
      - update
      - get
      - list
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
...
```

</details>

## Context

**Cluster(s):**

aws-dev

**Versions:** (seen in console's `/settings`)

- Core Version: kubeapps

**Desktop:** (if relevant)

- OS: Ubuntu  (changed to Ubuntu because of more recent packages)
- Version 20.04

**Additional context:** (add any other context about the problem here)

It has nothing to do with SELinux.

<details><summary>Possible solution(s)</summary>

https://stackoverflow.com/a/54787364:

```For others that see this issue with containers running as a different user, you need to ensure the uid/gid of the user inside the container has permissions to the file on the host. On production servers, this is often done by controlling the uid/gid in the image build process to match a uid/gid on the host that has access to the files (or even better, do not use host mounts in production).

A named volume is often preferred to host mounts because it will initialize the volume directory from the image directory, including any file ownership and permissions. This happens when the volume is empty and the container is created with the named volume.

MacOS users now have OSXFS which handles uid/gid's automatically between the Mac host and containers. One place it doesn't help with are files from inside the embedded VM that get mounted into the container, like /var/lib/docker.sock.

For development environments where the host uid/gid may change per developer, my preferred solution is to start the container with an entrypoint running as root, fix the uid/gid of the user inside the container to match the host volume uid/gid, and then use gosu to drop from root to the container user to run the application inside the container. The important script for this is fix-perms in my base image scripts, which can be found at: https://github.com/sudo-bmitch/docker-base

The important bit from the fix-perms script is:

# update the uid
if [ -n "$opt_u" ]; then
  OLD_UID=$(getent passwd "${opt_u}" | cut -f3 -d:)
  NEW_UID=$(stat -c "%u" "$1")
  if [ "$OLD_UID" != "$NEW_UID" ]; then
    echo "Changing UID of $opt_u from $OLD_UID to $NEW_UID"
    usermod -u "$NEW_UID" -o "$opt_u"
    if [ -n "$opt_r" ]; then
      find / -xdev -user "$OLD_UID" -exec chown -h "$opt_u" {} \;
    fi
  fi
fi
That gets the uid of the user inside the container, and the uid of the file, and if they do not match, calls usermod to adjust the uid. Lastly it does a recursive find to fix any files which have not changed uid's. I like this better than running a container with a -u $(id -u):$(id -g) flag because the above entrypoint code doesn't require each developer to run a script to start the container, and any files outside of the volume that are owned by the user will have their permissions corrected.

You can also have docker initialize a host directory from an image by using a named volume that performs a bind mount. This directory must exist in advance, and you need to provide an absolute path to the host directory, unlike host volumes in a compose file which can be relative paths. The directory must also be empty for docker to initialize it. Three different options for defining a named volume to a bind mount look like:

  # create the volume in advance
  $ docker volume create --driver local \
      --opt type=none \
      --opt device=/home/user/test \
      --opt o=bind \
      test_vol

  # create on the fly with --mount
  $ docker run -it --rm \
    --mount type=volume,dst=/container/path,volume-driver=local,volume-opt=type=none,volume-opt=o=bind,volume-opt=device=/home/user/test \
    foo

  # inside a docker-compose file
  ...
  volumes:
    bind-test:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/user/test
  ...
Lastly, if you try using user namespaces, you'll find that host volumes have permission issues because uid/gid's of the containers are shifted. In that scenario, it's probably easiest to avoid host volumes and only use named volumes.
```

</details>

**Comment by Morriz** [comment]
Lets create an issue where we promise to create something like this: https://gist.github.com/renzok/29c9e5744f1dffa392cf

And for now update the docs to say you can only run otomi cli in dev mode on OSX.

**Comment by Morriz** [comment]
closing in favor of #353
