### ISSUE TITLE
The otomi.isManaged flag shall be required

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#557]
**Describe the bug:**
The schema does not define the `otomi.isManaged` flag as required one.

**To Reproduce**

1. Prepare values where  `otomi.isManaged` flag  is not provided
2. Perform `otomi template`
2. Observe prometheus-operator failure

**Expected behavior:**
The `otomi validate-values` shall report error.

**Additional context:**
```

  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: drone-pipelines
---
# Source: raw/templates/resources.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: raw
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: raw
    app.kubernetes.io/part-of: otomi
    app.kubernetes.io/version: 0.2.3
    helm.sh/chart: raw-0.2.3
  name: team-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: team-admin
---
# Source: raw/templates/resources.yaml
apiVersion: scheduling.k8s.io/v1
description: This priority class should be used for Otomi High priority service pods only.
globalDefault: false
kind: PriorityClass
metadata:
  labels:
    app: raw
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: raw
    app.kubernetes.io/part-of: otomi
    app.kubernetes.io/version: 0.2.3
    helm.sh/chart: raw-0.2.3
  name: otomi-critical
value: 1000000
2021-08-30T08:59:22.867Z otomi:apply:error helmfile-init.yaml: basePath=.
2021-08-30T08:59:26.018Z otomi:apply:error Listing releases matching ^gatekeeper-operator$
2021-08-30T08:59:26.139Z otomi:apply:log gatekeeper-operator    default      1           2021-08-30 08:53:47.471479941 +0000 UTC    deployed    gatekeeper-v3.2.2    v3.2.2
2021-08-30T08:59:26.796Z otomi:apply:log Comparing release=gatekeeper-operator, chart=../charts/gatekeeper-operator
2021-08-30T08:59:26.838Z otomi:apply:error Listing releases matching ^vault-operator$
2021-08-30T08:59:26.965Z otomi:apply:log vault-operator    vault        1           2021-08-30 08:56:57.249787566 +0000 UTC    deployed    vault-operator-1.11.0    1.11.0
2021-08-30T08:59:28.552Z otomi:apply:log Comparing release=jobs-artifacts, chart=../charts/raw
Comparing release=knative-init, chart=/tmp/charts/knative-init
Comparing release=loki-artifacts, chart=../charts/raw
Comparing release=vault-operator, chart=../charts/vault-operator
2021-08-30T08:59:31.632Z otomi:apply:error hook[prepare[] logs | Building constraints artifacts from policies.
hook[prepare[] logs | Copying policies temporarily to /tmp/otomi/policies
hook[prepare[] logs | Clearing disallowed refs
hook[prepare[] logs | Generating konstrait files to /tmp/otomi/constraints
hook[prepare[] logs | Dereferencing schema: /home/app/stack/values-schema.yaml
hook[prepare[] logs | Wrote file: /tmp/otomi/compiled-schema.json
hook[prepare[] logs | Decorating template/constraints files with properties.
hook[prepare[] logs | Done
hook[prepare[] logs | Building constraints SUCCESS
hook[prepare[] logs |
2021-08-30T08:59:31.633Z otomi:apply:error Listing releases matching ^istio-operator$
2021-08-30T08:59:31.710Z otomi:apply:log istio-operator    default      1           2021-08-30 08:57:13.976531064 +0000 UTC    deployed    istio-operator-1.10.1
2021-08-30T08:59:33.399Z otomi:apply:log Comparing release=gatekeeper-artifacts, chart=../charts/gatekeeper-artifacts
Comparing release=istio-operator, chart=../charts/istio-operator
Comparing release=keycloak, chart=../charts/keycloak
Comparing release=vault-operator-artifacts, chart=../charts/raw
2021-08-30T08:59:34.186Z otomi:apply:log Comparing release=istio-operator-artifacts, chart=../charts/raw
Comparing release=kubernetes-external-secrets, chart=../charts/kubernetes-external-secrets
2021-08-30T08:59:34.224Z otomi:apply:error Listing releases matching ^kured$
2021-08-30T08:59:34.272Z otomi:apply:error in helmfile.d/helmfile-08.init.yaml: failed processing release prometheus-operator: failed to render values files "../values/prometheus-operator/prometheus-operator.gotmpl": failed to render [../values/prometheus-operator/prometheus-operator.gotmpl], because of template: stringTemplate:24:9: executing "stringTemplate" at <$v.otomi.isManaged>: map has no entry for key "isManaged"
2021-08-30T08:59:34.275Z otomi:global:error Error: Listing releases matching ^gatekeeper-operator$
helmfile-03.init.yaml: basePath=.
Listing releases matching ^vault-operator$
helmfile-05.init.yaml: basePath=.
hook[prepare[] logs | Building constraints artifacts from policies.
hook[prepare[] logs | Copying policies temporarily to /tmp/otomi/policies
hook[prepare[] logs | Clearing disallowed refs
hook[prepare[] logs | Generating konstrait files to /tmp/otomi/constraints
hook[prepare[] logs | Dereferencing schema: /home/app/stack/values-schema.yaml
hook[prepare[] logs | Wrote file: /tmp/otomi/compiled-schema.json
hook[prepare[] logs | Decorating template/constraints files with properties.
hook[prepare[] logs | Done
hook[prepare[] logs | Building constraints SUCCESS
hook[prepare[] logs | 
Listing releases matching ^istio-operator$
Listing releases matching ^kured$
in helmfile.d/helmfile-08.init.yaml: failed processing release prometheus-operator: failed to render values files "../values/prometheus-operator/prometheus-operator.gotmpl": failed to render [../values/prometheus-operator/prometheus-operator.gotmpl], because of template: stringTemplate:24:9: executing "stringTemplate" at <$v.otomi.isManaged>: map has no entry for key "isManaged"
    at hfCore (file:///home/app/stack/dist/common/hf.js:44:20)
    exit code: 1
    at ChildProcess.<anonymous> (file:///home/app/stack/node_modules/zx/index.mjs:68:22)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by j-zimnowoda** [comment]
@j-zimnowoda check if this is still valid

**Comment by Morriz** [comment]
closing as already put in `env.gotmpl`
