### ISSUE TITLE
Otomi deployment on AWS cluster  fails if `otomi.hasCloudLB` flag is not provided 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#558]
**Describe the bug:** 
Otomi deployment on AWS cluster  fails if `otomi.hasCloudLB` flag is not provided 

**To Reproduce**

1. Prepare values that does not contain `otomi.hasCloudLB`
2. Perform `otomi template`
3. Observe parsing error in helmfile-20.ingress.yaml

**Expected behavior:**
The validation routine shall require the `otomi.hasCloudLB` flag if `otomi.provider is `aws`

**Additional context:** 
```

            requests:
              storage: "1Gi"
2021-08-30T09:25:44.539Z otomi:apply:error Listing releases matching ^redis$
2021-08-30T09:25:44.606Z otomi:apply:error Upgrading release=oauth2-proxy-redis, chart=../charts/redis
2021-08-30T09:26:15.796Z otomi:apply:log Release "oauth2-proxy-redis" has been upgraded. Happy Helming!
NAME: oauth2-proxy-redis
LAST DEPLOYED: Mon Aug 30 09:25:44 2021
NAMESPACE: istio-system
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **
Redis(TM) can be accessed via port 6379 on the following DNS name from within your cluster:
    oauth2-proxy-redis-master.istio-system.svc.cluster.local
To get your password run:
    export REDIS_PASSWORD=$(kubectl get secret --namespace istio-system oauth2-proxy-redis -o jsonpath="{.data.redis-password}" | base64 --decode)
To connect to your Redis(TM) server:
1. Run a Redis(TM) pod that you can use as a client:
   kubectl run --namespace istio-system redis-client --restart='Never'  --env REDIS_PASSWORD=$REDIS_PASSWORD  --image docker.io/bitnami/redis:6.2.3-debian-10-r0 --command -- sleep infinity
   Use the following command to attach to the pod:
   kubectl exec --tty -i redis-client \
   --namespace istio-system -- bash
2. Connect using the Redis(TM) CLI:
   redis-cli -h oauth2-proxy-redis-master -a $REDIS_PASSWORD
To connect to your database from outside the cluster execute the following commands:
    kubectl port-forward --namespace istio-system svc/oauth2-proxy-redis-master 6379:6379 &
    redis-cli -h 127.0.0.1 -p 6379 -a $REDIS_PASSWORD
2021-08-30T09:26:15.796Z otomi:apply:error Listing releases matching ^oauth2-proxy-redis$
2021-08-30T09:26:15.882Z otomi:apply:log oauth2-proxy-redis    istio-system    2           2021-08-30 09:25:44.961170492 +0000 UTC    deployed    redis-14.1.1    6.2.3
2021-08-30T09:26:15.882Z otomi:apply:error UPDATED RELEASES:
NAME                 CHART             VERSION
oauth2-proxy-redis   ../charts/redis    14.1.1
2021-08-30T09:26:15.923Z otomi:apply:error Listing releases matching ^jaeger-operator$
2021-08-30T09:26:15.983Z otomi:apply:log jaeger-operator    jaeger-operator    1           2021-08-30 09:23:46.980846898 +0000 UTC    deployed    jaeger-operator-2.21.4    1.25.0
2021-08-30T09:26:15.984Z otomi:apply:error Listing releases matching ^kiali-operator$
2021-08-30T09:26:16.033Z otomi:apply:log kiali-operator    kiali-operator    1           2021-08-30 09:23:46.938472424 +0000 UTC    deployed    kiali-operator-1.39.0    v1.39.0
2021-08-30T09:26:18.732Z otomi:apply:log Comparing release=grafana-dashboards, chart=../charts/grafana-dashboards
Comparing release=jaeger-operator, chart=../charts/jaeger-operator
Comparing release=kiali-operator, chart=../charts/kiali-operator
Comparing release=loki, chart=../charts/loki
Comparing release=prometheus-blackbox-exporter, chart=../charts/prometheus-blackbox-exporter
Comparing release=promtail, chart=../charts/promtail
2021-08-30T09:26:18.732Z otomi:apply:error Listing releases matching ^prometheus-msteams$
2021-08-30T09:26:18.943Z otomi:apply:error Listing releases matching ^sitespeed$
2021-08-30T09:26:19.136Z otomi:apply:error Listing releases matching ^weave-scope$
2021-08-30T09:26:20.180Z otomi:apply:log Comparing release=team-ns-admin, chart=../charts/team-ns
2021-08-30T09:26:21.036Z otomi:apply:log Comparing release=job-keycloak, chart=../charts/jobs
2021-08-30T09:26:21.060Z otomi:apply:error in helmfile.d/helmfile-20.ingress.yaml: error during helmfile-20.ingress.yaml.part.1 parsing: template: stringTemplate:6:55: executing "stringTemplate" at <$v.otomi.hasCloudLB>: map has no entry for key "hasCloudLB"
2021-08-30T09:26:21.063Z otomi:global:error Error: Listing releases matching ^gatekeeper-operator$
helmfile-03.init.yaml: basePath=.
Listing releases matching ^vault-operator$
helmfile-05.init.yaml: basePath=.
hook[prepare[] logs | Building constraints artifacts from policies.
hook[prepare[] logs | Copying policies temporarily to /tmp/otomi/policies
hook[prepare[] logs | Clearing disallowed refs
hook[prepare[] logs | Generating konstrait files to /tmp/otomi/constraints
hook[prepare[] logs | Dereferencing schema: /home/app/stack/values-schema.yaml
hook[prepare[] logs | Wrote file: /tmp/otomi/compiled-schema.json
hook[prepare[] logs | Decorating template/constraints files with properties.
hook[prepare[] logs | Done
hook[prepare[] logs | Building constraints SUCCESS
hook[prepare[] logs | 
Listing releases matching ^istio-operator$
Listing releases matching ^kured$
Listing releases matching ^redis$
Upgrading release=oauth2-proxy-redis, chart=../charts/redis
Listing releases matching ^oauth2-proxy-redis$
UPDATED RELEASES:
NAME                 CHART             VERSION
oauth2-proxy-redis   ../charts/redis    14.1.1
Listing releases matching ^jaeger-operator$
Listing releases matching ^kiali-operator$
Listing releases matching ^prometheus-msteams$
Listing releases matching ^sitespeed$
Listing releases matching ^weave-scope$
in helmfile.d/helmfile-20.ingress.yaml: error during helmfile-20.ingress.yaml.part.1 parsing: template: stringTemplate:6:55: executing "stringTemplate" at <$v.otomi.hasCloudLB>: map has no entry for key "hasCloudLB"
    at hfCore (file:///home/app/stack/dist/common/hf.js:44:20)
    exit code: 1
    at ChildProcess.<anonymous> (file:///home/app/stack/node_modules/zx/index.mjs:68:22)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by Dunky13** [comment]
Does this commit fix this issue: https://github.com/redkubes/otomi-core/commit/cef222cb723f9f2e47b83123354f6772cf10d354?

**Comment by Morriz** [comment]
idd
