### ISSUE TITLE
<$cluster.cluster.provider>: map has no entry for key "provider"

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#577]
**Describe the bug:**
If I open otomi-core in remote container, I can not bootstrap and I receive this error: 

```

app@88190dd02017:/workspaces/otomi-core$ binzx/otomi bootstrap 
Debugger attached.
  otomi:bootstrap:log Copying basic values +0ms
  otomi:bootstrap:log Copying Otomi Console Setup +401ms
  otomi:global:error Error: in /workspaces/otomi-core/helmfile.tpl/helmfile-dump.yaml: error during ../helmfile.d/snippets/env.gotmpl.part.0 parsing: template: stringTemplate:6:25: executing "stringTemplate" at <$cluster.cluster.provider>: map has no entry for key "provider"
  otomi:global:error     at hfCore (file:///workspaces/otomi-core/dist/common/hf.js:44:20)
  otomi:global:error     exit code: 1
  otomi:global:error     at ChildProcess.<anonymous> (file:///workspaces/otomi-core/node_modules/zx/index.mjs:68:22)
  otomi:global:error     at ChildProcess.emit (node:events:394:28)
  otomi:global:error     at maybeClose (node:internal/child_process:1067:16)
  otomi:global:error     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  otomi:global:error     at Process.callbackTrampoline (node:internal/async_hooks:130:17) +0ms

```

**To Reproduce**
1- open otomi-core in remote-container mode 
2- run binzx/otomi bootstrap

**Comment by Dunky13** [comment]
Fixed in https://github.com/redkubes/otomi-core/pull/575/files#diff-7b86a94839cdb5c6fa1d648db23c4e6d48e533ac67652d62b24b0be3932de38fR56

**Comment by mojtabaimani** [comment]
I don't know why. by the way markdown problem is only in side window mode. 
if you open it in new window it will work.

**Comment by mojtabaimani** [comment]
the same problem in the local machine exist as well.

**Comment by j-zimnowoda** [comment]
Are you sure that `env` directory is mapped properly?

**Comment by Morriz** [comment]
closing as exotic and won't fix because this bug report is currently not pointing to any bug in this repo
