### ISSUE TITLE
Some files are not encrypted

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#617]
**Describe the bug:** (a clear and concise description of what the bug is)

The otomi deployment cannot proceed do to error with unencrypted file.
**To Reproduce**

1. deploy otomi helm chart with `kms.sops` configured
2. Observe error that `File is not encrypted: env/charts/secrets.drone.yaml`

```
2021-10-07T11:46:26.499Z otomi:encrypt:info Starting encryption
2021-10-07T11:46:26.500Z otomi:encrypt:debug getAllSecretFiles:  [
  'env/charts/secrets.drone.yaml',
  'env/charts/secrets.gitea.yaml',
  'env/charts/secrets.harbor.yaml',
  'env/charts/secrets.keycloak.yaml',
  'env/charts/secrets.kubeapps.yaml',
  'env/charts/secrets.loki.yaml',
  'env/charts/secrets.oauth2-proxy-redis.yaml',
  'env/charts/secrets.oauth2-proxy.yaml',
  'env/charts/secrets.otomi-api.yaml',
  'env/charts/secrets.prometheus-operator.yaml',
  'env/charts/secrets.redis-shared.yaml',
  'env/secrets.settings.yaml',
  'env/secrets.teams.yaml'
]
2021-10-07T11:46:26.500Z otomi:encrypt:debug Checking prerequisites for the (de,en)crypt action
2021-10-07T11:46:26.501Z otomi:encrypt:debug runOnSecretFiles: helm secrets enc
2021-10-07T11:46:26.501Z otomi:encrypt:debug Found decrypted env/charts/secrets.drone.yaml.dec
2021-10-07T11:46:26.501Z otomi:encrypt:debug encTS.mtime:  2021-10-07T11:46:26.351Z
2021-10-07T11:46:26.501Z otomi:encrypt:debug decTS.mtime:  2021-10-07T11:46:26.495Z
2021-10-07T11:46:26.501Z otomi:encrypt:info Skipping encryption for env/charts/secrets.drone.yaml as it has not changed
2021-10-07T11:46:26.501Z otomi:encrypt:debug Found decrypted env/charts/secrets.gitea.yaml.dec
2021-10-07T11:46:26.501Z otomi:encrypt:debug encTS.mtime:  2021-10-07T11:46:26.351Z
2021-10-07T11:46:26.501Z otomi:encrypt:debug decTS.mtime:  2021-10-07T11:46:26.495Z
2021-10-07T11:46:26.501Z otomi:encrypt:info Skipping encryption for env/charts/secrets.gitea.yaml as it has not changed
2021-10-07T11:46:26.501Z otomi:encrypt:debug Found decrypted env/charts/secrets.harbor.yaml.dec
2021-10-07T11:46:26.501Z otomi:encrypt:debug encTS.mtime:  2021-10-07T11:46:26.351Z
2021-10-07T11:46:26.501Z otomi:encrypt:debug decTS.mtime:  2021-10-07T11:46:26.495Z
2021-10-07T11:46:26.501Z otomi:encrypt:info Skipping encryption for env/charts/secrets.harbor.yaml as it has not changed
2021-10-07T11:46:26.501Z otomi:encrypt:debug Found decrypted env/charts/secrets.keycloak.yaml.dec
2021-10-07T11:46:26.501Z otomi:encrypt:debug encTS.mtime:  2021-10-07T11:46:26.351Z
2021-10-07T11:46:26.501Z otomi:encrypt:debug decTS.mtime:  2021-10-07T11:46:26.495Z
2021-10-07T11:46:26.501Z otomi:encrypt:info Skipping encryption for env/charts/secrets.keycloak.yaml as it has not changed
2021-10-07T11:46:26.501Z otomi:encrypt:debug Found decrypted env/charts/secrets.kubeapps.yaml.dec
2021-10-07T11:46:26.501Z otomi:encrypt:debug encTS.mtime:  2021-10-07T11:46:26.351Z
2021-10-07T11:46:26.501Z otomi:encrypt:debug decTS.mtime:  2021-10-07T11:46:26.495Z
2021-10-07T11:46:26.502Z otomi:encrypt:info Skipping encryption for env/charts/secrets.kubeapps.yaml as it has not changed
2021-10-07T11:46:26.502Z otomi:encrypt:debug Found decrypted env/charts/secrets.loki.yaml.dec
2021-10-07T11:46:26.502Z otomi:encrypt:debug encTS.mtime:  2021-10-07T11:46:26.351Z
2021-10-07T11:46:26.502Z otomi:encrypt:debug decTS.mtime:  2021-10-07T11:46:26.495Z
2021-10-07T11:46:26.502Z otomi:encrypt:info Skipping encryption for env/charts/secrets.loki.yaml as it has not changed
2021-10-07T11:46:26.502Z otomi:encrypt:debug Did not find decrypted /home/app/stack/env/env/charts/secrets.oauth2-proxy-redis.yaml.dec
2021-10-07T11:46:26.502Z otomi:encrypt:debug helm secrets enc env/charts/secrets.oauth2-proxy-redis.yaml
2021-10-07T11:46:26.504Z otomi:encrypt:debug Found decrypted env/charts/secrets.oauth2-proxy.yaml.dec
2021-10-07T11:46:26.504Z otomi:encrypt:debug encTS.mtime:  2021-10-07T11:46:26.351Z
2021-10-07T11:46:26.505Z otomi:encrypt:debug decTS.mtime:  2021-10-07T11:46:26.495Z
2021-10-07T11:46:26.505Z otomi:encrypt:info Skipping encryption for env/charts/secrets.oauth2-proxy.yaml as it has not changed
2021-10-07T11:46:26.505Z otomi:encrypt:debug Did not find decrypted /home/app/stack/env/env/charts/secrets.otomi-api.yaml.dec
2021-10-07T11:46:26.505Z otomi:encrypt:debug helm secrets enc env/charts/secrets.otomi-api.yaml
2021-10-07T11:46:26.507Z otomi:encrypt:debug Did not find decrypted /home/app/stack/env/env/charts/secrets.prometheus-operator.yaml.dec
2021-10-07T11:46:26.507Z otomi:encrypt:debug helm secrets enc env/charts/secrets.prometheus-operator.yaml
2021-10-07T11:46:27.018Z otomi:encrypt:debug Missing env/charts/secrets.otomi-api.yaml.dec, skipping...
2021-10-07T11:46:27.018Z otomi:encrypt:debug Missing env/charts/secrets.oauth2-proxy-redis.yaml.dec, skipping...
2021-10-07T11:46:27.028Z otomi:encrypt:debug Missing env/charts/secrets.prometheus-operator.yaml.dec, skipping...
2021-10-07T11:46:27.028Z otomi:encrypt:debug Did not find decrypted /home/app/stack/env/env/charts/secrets.redis-shared.yaml.dec
2021-10-07T11:46:27.028Z otomi:encrypt:debug helm secrets enc env/charts/secrets.redis-shared.yaml
2021-10-07T11:46:27.031Z otomi:encrypt:debug Found decrypted env/secrets.settings.yaml.dec
2021-10-07T11:46:27.031Z otomi:encrypt:debug encTS.mtime:  2021-10-07T11:46:26.423Z
2021-10-07T11:46:27.032Z otomi:encrypt:debug decTS.mtime:  2021-10-07T11:46:26.495Z
2021-10-07T11:46:27.032Z otomi:encrypt:info Skipping encryption for env/secrets.settings.yaml as it has not changed
2021-10-07T11:46:27.032Z otomi:encrypt:debug Did not find decrypted /home/app/stack/env/env/secrets.teams.yaml.dec
2021-10-07T11:46:27.032Z otomi:encrypt:debug helm secrets enc env/secrets.teams.yaml
2021-10-07T11:46:27.519Z otomi:encrypt:debug Missing env/charts/secrets.redis-shared.yaml.dec, skipping...
2021-10-07T11:46:32.057Z otomi:encrypt:debug Missing env/secrets.teams.yaml.dec, skipping...
2021-10-07T11:46:32.057Z otomi:encrypt:info Encryption is done
2021-10-07T11:46:32.057Z otomi:bootstrap:log You can now use the otomi CLI
2021-10-07T11:46:32.057Z otomi:bootstrap:log Done bootstrapping values
2021-10-07T11:46:32.057Z otomi:decrypt:info Starting decryption
2021-10-07T11:46:32.058Z otomi:decrypt:debug getAllSecretFiles:  [
  'env/charts/secrets.drone.yaml',
  'env/charts/secrets.gitea.yaml',
  'env/charts/secrets.harbor.yaml',
  'env/charts/secrets.keycloak.yaml',
  'env/charts/secrets.kubeapps.yaml',
  'env/charts/secrets.loki.yaml',
  'env/charts/secrets.oauth2-proxy-redis.yaml',
  'env/charts/secrets.oauth2-proxy.yaml',
  'env/charts/secrets.otomi-api.yaml',
  'env/charts/secrets.prometheus-operator.yaml',
  'env/charts/secrets.redis-shared.yaml',
  'env/secrets.settings.yaml',
  'env/secrets.teams.yaml'
]
2021-10-07T11:46:32.058Z otomi:decrypt:debug Checking prerequisites for the (de,en)crypt action
2021-10-07T11:46:32.058Z otomi:decrypt:debug runOnSecretFiles: helm secrets dec
2021-10-07T11:46:32.058Z otomi:decrypt:debug helm secrets dec env/charts/secrets.drone.yaml
2021-10-07T11:46:32.061Z otomi:decrypt:debug helm secrets dec env/charts/secrets.gitea.yaml
2021-10-07T11:46:32.064Z otomi:decrypt:debug helm secrets dec env/charts/secrets.harbor.yaml
2021-10-07T11:46:32.066Z otomi:decrypt:debug helm secrets dec env/charts/secrets.keycloak.yaml
2021-10-07T11:46:32.071Z otomi:decrypt:debug helm secrets dec env/charts/secrets.kubeapps.yaml
2021-10-07T11:46:32.175Z otomi:decrypt:error Error: [helm-secrets] File is not encrypted: env/charts/secrets.drone.yaml
Error: plugin "secrets" exited with error
    at file:///home/app/stack/dist/src/common/crypt.js:41:30
    exit code: 1
    at ChildProcess.<anonymous> (file:///home/app/stack/node_modules/zx/index.mjs:68:22)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2021-10-07T11:46:32.175Z otomi:decrypt:info Decryption is done
2021-10-07T11:46:32.175Z otomi:bootstrap:info Initializing values repo.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

ProcessOutput [Error]: [helm-secrets] File is not encrypted: env/charts/secrets.drone.yaml
Error: plugin "secrets" exited with error
    at file:///home/app/stack/dist/src/common/crypt.js:41:30
    exit code: 1
    at ChildProcess.<anonymous> (file:///home/app/stack/node_modules/zx/index.mjs:68:22)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

```
**Expected behavior:** (a clear and concise description of what you expected to happen)
all files with `secrets.` name prefix are encrypted.

**Comment by Morriz** [comment]
> The genSops needs to be rewritten so it can generate sops file even if there is no env/ dir in place yet

Where would it write it then? This sound strange to me

**Comment by j-zimnowoda** [comment]
It would write sops file to the same place as it used to do
