### ISSUE TITLE
otomi commit cannot push to repo

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#698]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Deploy otomi from chart and download repo
1. Make change in values repo
1. `otomi commit` and observe error
```
> otomi commit                                     (⎈ gke_otomi-quickstart_europe-west1_otomi-gks-jeho:default)
  otomi:prepareEnvironment:info Checking environment +0ms
  otomi:validate-values:log Values validation STARTED +0ms
  otomi:validate-values:info Loading values-schema.yaml +0ms
  otomi:validate-values:info Validating values +374ms
  otomi:validate-values:log Values validation SUCCESSFUL +803ms
  otomi:commit:info Preparing values +0ms
GET https://gitea.34.79.43.2.nip.io/otomi/values.git 404 !== 200
  otomi:waitTillAvailable:error Error: Wrong status code: 404
  otomi:waitTillAvailable:error     at /Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/k8s.ts:190:21
  otomi:waitTillAvailable:error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  otomi:waitTillAvailable:error     at async waitTillAvailable (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/k8s.ts:185:3)
  otomi:waitTillAvailable:error     at async commit (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/cmd/commit.ts:145:5)
  otomi:waitTillAvailable:error     at async Object.handler (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/cmd/commit.ts:179:5) +0ms
GET https://gitea.34.79.43.2.nip.io/otomi/values.git 404 !== 200
```
**Expected behavior:** (a clear and concise description of what you expected to happen)

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

**Smartphone:** (if relevant)

**Additional context:** (add any other context about the problem here)

**Comment by Morriz** [comment]
strange...that url gives a 404...so maybe not strange?

**Comment by Morriz** [comment]
fixed in master
