### ISSUE TITLE
Running otomi CLI in development mode results in waitTillAvailable error

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#714]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

Perform
```
./binzx/otomi apply 
```
Observe:
```
  otomi:common:k8s:waitTillAvailable:error GET git@github.com:redkubes/otomi-stack.git TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/node_modules/node-fetch/lib/index.js:1327:9)
    at /Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/node_modules/node-fetch/lib/index.js:1432:19
    at new Promise (<anonymous>)
    at fetch (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/node_modules/node-fetch/lib/index.js:1429:9)
    at /Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/src/common/k8s.ts:194:30
    at RetryOperation.runAttempt [as _fn] (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/node_modules/async-retry/lib/index.js:42:15)
    at Timeout._onTimeout (/Users/jehoszafatzimnowoda/workspace/otomi/otomi-core/node_modules/retry/lib/retry_operation.js:85:10)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) +30s
```

**Expected behavior:** (a clear and concise description of what you expected to happen)
No time out issue

**Comment by Morriz** [comment]
@j-zimnowoda I think this is due to having conflicting env vars. Can you try in a clean terminal?

**Comment by j-zimnowoda** [comment]
outdated
