### ISSUE TITLE
Knative installation failure

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#803]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Deploy otomi witt k8s version 1.21
2.  Activate knative and deploy 
3. Observe error:
```
hook[presync] logs | 
55s35840Upgrading release=knative-serving, chart=../charts/raw
55s35841
55s35842FAILED RELEASES:
55s35843NAME
55s35844knative-serving
55s35845in helmfile.d/helmfile-09.init.yaml: failed processing release knative-serving: command "/home/app/tools/helm" exited with non-zero status:
55s35846
55s35847PATH:
55s35848  /home/app/tools/helm
55s35849
55s35850ARGS:
55s35851  0: helm (4 bytes)
55s35852  1: upgrade (7 bytes)
55s35853  2: --install (9 bytes)
55s35854  3: --reset-values (14 bytes)
55s35855  4: knative-serving (15 bytes)
55s35856  5: ../charts/raw (13 bytes)
55s35857  6: --wait (6 bytes)
55s35858  7: --timeout (9 bytes)
55s35859  8: 1200s (5 bytes)
55s35860  9: --atomic (8 bytes)
55s35861  10: --create-namespace (18 bytes)
55s35862  11: --namespace (11 bytes)
55s35863  12: knative-serving (15 bytes)
55s35864  13: --values (8 bytes)
55s35865  14: /tmp/helmfile3794259560/knative-serving-knative-serving-values-6598dcbd89 (73 bytes)
55s35866  15: --values (8 bytes)
55s35867  16: /tmp/helmfile3810059575/knative-serving-knative-serving-values-74b97887db (73 bytes)
55s35868  17: --history-max (13 bytes)
55s35869  18: 3 (1 bytes)
55s35870
55s35871ERROR:
55s35872  exit status 1
55s35873
55s35874EXIT STATUS
55s35875  1
55s35876
55s35877STDERR:
55s35878  Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "KnativeServing" in version "operator.knative.dev/v1alpha1"
55s35879
55s35880COMBINED OUTPUT:
55s35881  Release "knative-serving" does not exist. Installing it now.
55s35882  Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "KnativeServing" in version "operator.knative.dev/v1alpha1"
55s35883    at hfCore (/home/app/stack/dist/src/common/hf.js:43:30)
55s35884    exit code: 1
55s35885    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/dist/bundle.cjs:15261:22)
55s35886    at ChildProcess.emit (node:events:527:28)
55s35887    at maybeClose (node:internal/child_process:1092:16)
55s35888    at Socket.<anonymous> (node:internal/child_process:451:11)
55s35889    at Socket.emit (node:events:527:28)
55s35890    at Pipe.<anonymous> (node:net:709:12)
55s3589156s
```

[Full log](https://app.zenhub.com/files/200118806/cafed41c-748d-4f5c-843e-9387475c3f07/download)

**Expected behavior:** (a clear and concise description of what you expected to happen)
Successful installation of knative
**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: azure

**Versions:** (seen in console's `/settings`)

- Core Version main

**Comment by diabhey** [comment]
t was tested on `v0.16.4`  and not `main`. So (activating knative) is not an issue.
